# Conexion a la base de datos MySQL (MySQL Workbench)
spring.datasource.url=jdbc:mysql://localhost:3306/proyectodemospbt?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234

# Configuracion de JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Puerto donde corre la aplicacion
server.port=9000

# Nombre de la app
spring.application.name=demo